import type { AppState, Opportunity, Settings } from "./types";

export const defaultSettings: Settings = {
  buyerProtectionRate: 0.05,
  buyerProtectionFixed: 0.7,
  defaultShipping: 3.28,
  defaultPreparation: 1.5,
  defaultRiskReserve: 2,
  minimumProfit: 15,
  minimumRoi: 40,
  minimumProbability30d: 0.55,
  targetHoldingDays: 45,
  negotiationBuffer: 12,
};

const now = new Date();
const dateAgo = (days: number) =>
  new Date(now.getTime() - days * 86_400_000).toISOString();

const base = (
  input: Partial<Opportunity> & Pick<Opportunity, "id" | "title">,
): Opportunity => ({
  id: input.id,
  createdAt: input.createdAt ?? dateAgo(0),
  updatedAt: input.updatedAt ?? dateAgo(0),
  source: input.source ?? "Vinted",
  sourceUrl: input.sourceUrl ?? "",
  title: input.title,
  brand: input.brand ?? "",
  model: input.model ?? "",
  category: input.category ?? "Vêtement",
  size: input.size ?? "",
  condition: input.condition ?? "very_good",
  description: input.description ?? "",
  purchasePrice: input.purchasePrice ?? 0,
  protectionFee: input.protectionFee ?? 0.7,
  inboundShipping: input.inboundShipping ?? 3.28,
  preparationCost: input.preparationCost ?? 1.5,
  riskReserve: input.riskReserve ?? 2,
  expectedSalePrice: input.expectedSalePrice ?? 0,
  salePriceLow: input.salePriceLow ?? 0,
  salePriceHigh: input.salePriceHigh ?? 0,
  probability30d: input.probability30d ?? 0.5,
  estimatedDaysToSell: input.estimatedDaysToSell ?? 30,
  riskLevel: input.riskLevel ?? "moderate",
  status: input.status ?? "watching",
  notes: input.notes ?? "",
  images: input.images ?? [],
  sku: input.sku ?? "",
  storageBin: input.storageBin ?? "",
  listingDraft: input.listingDraft ?? null,
  listedAt: input.listedAt ?? "",
  soldAt: input.soldAt ?? "",
  actualSalePrice: input.actualSalePrice ?? null,
  extraSaleCosts: input.extraSaleCosts ?? 0,
});

export function createDemoState(): AppState {
  return {
    version: 1,
    settings: { ...defaultSettings },
    opportunities: [
      base({
        id: "demo-carhartt",
        createdAt: dateAgo(0),
        title: "Veste Carhartt Detroit marron taille M",
        brand: "Carhartt",
        model: "Detroit",
        category: "Veste de travail",
        size: "M",
        purchasePrice: 24,
        protectionFee: 1.9,
        expectedSalePrice: 68,
        salePriceLow: 54,
        salePriceHigh: 78,
        probability30d: 0.76,
        estimatedDaysToSell: 16,
        riskLevel: "low",
        description: "Marron, doublure en bon état. Légère patine aux manches.",
      }),
      base({
        id: "demo-levis",
        createdAt: dateAgo(3),
        updatedAt: dateAgo(2),
        title: "Jean Levi's 501 W32 L32 bleu",
        brand: "Levi's",
        model: "501",
        category: "Jean droit",
        size: "W32 L32",
        purchasePrice: 17,
        protectionFee: 1.55,
        expectedSalePrice: 42,
        salePriceLow: 34,
        salePriceHigh: 48,
        probability30d: 0.64,
        estimatedDaysToSell: 24,
        riskLevel: "low",
        status: "ordered",
        notes: "Colis attendu cette semaine.",
      }),
      base({
        id: "demo-adidas",
        createdAt: dateAgo(9),
        updatedAt: dateAgo(6),
        title: "Track jacket Adidas vintage noire L",
        brand: "Adidas",
        model: "Track jacket vintage",
        category: "Veste de sport",
        size: "L",
        purchasePrice: 14,
        protectionFee: 1.4,
        expectedSalePrice: 39,
        salePriceLow: 29,
        salePriceHigh: 45,
        probability30d: 0.61,
        estimatedDaysToSell: 27,
        riskLevel: "moderate",
        status: "received",
        sku: "ADID-TRAC-0001",
        storageBin: "B-04",
        notes: "Micro-accroc près de la poche droite à photographier.",
      }),
      base({
        id: "demo-newbalance",
        createdAt: dateAgo(22),
        updatedAt: dateAgo(18),
        title: "New Balance 2002R gris 42,5",
        brand: "New Balance",
        model: "2002R",
        category: "Baskets",
        size: "42,5",
        purchasePrice: 34,
        protectionFee: 2.4,
        preparationCost: 3,
        riskReserve: 4,
        expectedSalePrice: 72,
        salePriceLow: 58,
        salePriceHigh: 82,
        probability30d: 0.59,
        estimatedDaysToSell: 31,
        riskLevel: "moderate",
        status: "listed",
        sku: "NEWB-2002-0002",
        storageBin: "C-02",
        listedAt: dateAgo(18),
        listingDraft: {
          title: "New Balance · 2002R · Baskets · 42,5",
          description:
            "New Balance 2002R grises, taille 42,5. Très bon état général. Photos de l’article réel.",
          price: 72,
          packageSize: "Moyen",
        },
      }),
      base({
        id: "demo-controller",
        createdAt: dateAgo(38),
        updatedAt: dateAgo(12),
        title: "Manette Xbox Series noire",
        brand: "Microsoft",
        model: "Xbox Series Controller",
        category: "Manette",
        purchasePrice: 18,
        protectionFee: 1.6,
        preparationCost: 1,
        riskReserve: 3,
        expectedSalePrice: 38,
        salePriceLow: 33,
        salePriceHigh: 42,
        probability30d: 0.72,
        estimatedDaysToSell: 19,
        riskLevel: "moderate",
        status: "sold",
        sku: "MICR-XBOX-0003",
        storageBin: "",
        listedAt: dateAgo(31),
        soldAt: dateAgo(12),
        actualSalePrice: 37,
        extraSaleCosts: 0.6,
      }),
      base({
        id: "demo-zara",
        createdAt: dateAgo(1),
        updatedAt: dateAgo(1),
        title: "Chemise Zara homme taille M",
        brand: "Zara",
        category: "Chemise",
        size: "M",
        purchasePrice: 11,
        protectionFee: 1.25,
        expectedSalePrice: 19,
        salePriceLow: 14,
        salePriceHigh: 23,
        probability30d: 0.43,
        estimatedDaysToSell: 48,
        riskLevel: "low",
        status: "skipped",
      }),
    ],
  };
}

export function createEmptyState(): AppState {
  return {
    version: 1,
    settings: { ...defaultSettings },
    opportunities: [],
  };
}

